version: '3.8'

services:
  rag-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    entrypoint: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8010"]
    ports:
      - "8010:8010"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - .:/app

  postgres:
    image: ankane/pgvector
    container_name: xavigate_postgres
    restart: always
    environment:
      POSTGRES_DB: xavigate
      POSTGRES_USER: xavigate_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    container_name: xavigate_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  jupyter:
    image: jupyter/base-notebook
    container_name: xavigate_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  pgdata:
  chroma_data: